version: '3.8'

services:

  psql:
    container_name: metaweave-twitter-bridge.psql
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: 'password'
    volumes:
      - psql.db:/var/lib/postgresql/data
  
  app:
    container_name: metaweave-twitter-bridge.app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3010:3000
    depends_on:
      - psql
    restart: always

volumes:
  psql.db: