version: '3.8'

services:

  psql:
    image: postgres:14
    container_name: argora-twitter-bridge.psql
    restart: always
    environment:
      POSTGRES_PASSWORD: 'password'
    volumes:
      - psql.db:/var/lib/postgresql/data
  
  frontend:
    build:
      context: react/.
      dockerfile: Dockerfile
    ports:
      - 3010:3000

volumes:
  psql.db: